### ISSUE TITLE
Add preference to avoid symlink creation

### ISSUE THREAD

**Issue by elbrujohalcon** [esl/erlang-osx-installer#111]
Each time the default release is changed, the installer symlinks `/usr/local/bin/erl` (and others) with the ones in the default release.
This should be optional. A boolean flag (probably ticked by default) should appear in the preferences window so that the user can choose if that is what he wants or not.
Upon ticking the checkbox, the symlink should be created as well. When unticking, nothing should happen.

**Comment by bryanhuntesl** [comment]
Uses a path override in .profile now - no symlinking - reopen if I'm incorrect.
