### ISSUE TITLE
Make the Application aware of the old version of the installer and remove it if found.

### ISSUE THREAD

**Issue by kentron** [esl/erlang-osx-installer#123]
This issues presents some problems/questions:
The installer complains when trying to delete the folder containing Erlang due lack of privileges. 

1. According to @ https://github.com/beltex/SMCKit/issues/2, using Authorization Services  with Swift is broken since:
a. AuthorizationExecuteWithPrivileges() is deprecated
b. Swift class FileManager has no way to request permissions.
c. An alternative is to write a helper via launchd, but doing this will need code signing. (More details here:       
http://stackoverflow.com/questions/6841937/authorizationexecutewithprivileges-is-deprecated)
c. It looks like the only way to prompt the user to escalate privileges and without code signing is by using class NSAppleScript as
described here: http://stackoverflow.com/questions/6841937/authorizationexecutewithprivileges-is-deprecated using AppleScript. (I tested it and works).

On usability:
1. The installer is currently checking the presence of the old installer at "first launch". 
a. Should it be done each time the application launches? 
ab. Should it prompt only if it's an updated version?

Other approach:
a. Should this issue be	solved just by just changing	the prompt to	 "A deprecated ESL Erlang installation has been
found at /xxx/xx/xx.."  and leave the user the decision to manually uninstall the old version?

**Comment by bryanhuntesl** [comment]
closing out - pending confirmation
