### ISSUE TITLE
iTerm not being detected (reported by Bartlomiej Gorny)

### ISSUE THREAD

**Issue by kentron** [esl/erlang-osx-installer#129]
from his report:
In preferences, "Terminal Application" box shows ony "Terminal" (does not discover iTerm)

This is related with #127. Since new versions of OS X arise, the support for Scripting Bridge is less reliable. The application is currently opening Terminal.app using scripting bridge. This didn't work well with new versions of iTerm that seems to be dropping support for AppleScript (which is accessed via ScriptingBridge). 
My suggestion is that it would be better to eliminate SB and replace it by NSWorkSpace methods.

**Comment by bryanhuntesl** [comment]
Not a huge fan of iTerm - lets reopen if users specifically request
