### ISSUE TITLE
Link default to the root path, not bin

### ISSUE THREAD

**Issue by elbrujohalcon** [esl/erlang-osx-installer#136]
Can we make `~/.erlanginstaller/default` link to, e.g., `~/.erlanginstaller/19.3` instead of `~/.erlanginstaller/19.3/bin`?
That way I can have `~/.erlanginstaller/default/lib` on my _Sublime Text_ pointing to the default version of Erlang/OTP's source code all the time? ;)
Don't forget to also put `~/.erlanginstaller/default/bin` in the `$PATH` instead of `~/.erlanginstaller/default`.

**Comment by bryanhuntesl** [comment]
Fixed
