### ISSUE TITLE
Uninstall previous ESL Erlang installation

### ISSUE THREAD

**Issue by jfacorro** [esl/erlang-osx-installer#26]
The first time the application runs, check if there is an ESL installation from the package installer, if so remove the following items:
1. [ ] `/usr/local/lib/erlang`.
2. [x] Symlinks to the Erlang executables located in the directory from the previous items. 
3. [x] `ErlangSolutionUpdater` agent from the Login Items.
4. [x] `MacUpdaterSwift` agent from the Login Items.

We might want to ask the user for confirmation before doing 1 & 2.

**Comment by bryanhuntesl** [comment]
Better that it doesn't mess about with symlinks as root.
