### ISSUE TITLE
New installer logs? - Feedback from user

### ISSUE THREAD

**Issue by sebacancinos** [esl/erlang-osx-installer#94]
Feedback from user:

![image](https://cloud.githubusercontent.com/assets/562966/19039829/ddea82d2-8957-11e6-9c99-95a47c42d648.png)
So I answer YES and nothing else appears to happen.

So I peeked in Activity Monitor.  Sure enough after I press YES the process terminates.

Are there any logs so I can give you more actionable data?\

Thanks,
David

**Comment by bryanhuntesl** [comment]
Stale - closing out.
